# Generated by Django 2.2.16 on 2021-11-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20211125_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(help_text='Тут могут быть правила, описания группы и т.д.', verbose_name='Описания сообщества'),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(help_text='Придумайте название для сообщества', max_length=200, verbose_name='Название группы'),
        ),
    ]
