# Generated by Django 2.2.16 on 2021-11-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(help_text='выскажите своё мнение', verbose_name='коментарий к посту'),
        ),
    ]
